name: Test Email

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      mailhog:
        image: mailhog/mailhog:v1.0.1
        ports:
          - 1025:1025
          - 8025:8025

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Python dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          extensions: mysqli
          coverage: none
          
      - name: Check if MailHog is running
        run: |
          curl -s http://localhost:8025 > /dev/null
          if [ $? -ne 0 ]; then
            echo "MailHog is not running!"
            exit 1
          else
            echo "MailHog is running."
          fi

      - name: Install WP-CLI
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp

      - name: Set up WordPress test environment
        run: |
          # Download and configure WordPress
          wp core download --path=wordpress
          wp config create --dbname=wordpress --dbuser=root --dbpass=root --dbhost=127.0.0.1:3306 --path=wordpress
          wp core install --url="http://localhost" --title="Test Site" --admin_user="admin" --admin_password="password" --admin_email="admin@example.com" --path=wordpress


      - name: Install and activate WP Mail SMTP plugin
        run: |
          wp plugin install wp-mail-smtp --activate --path=wordpress

      - name: Configure WP Mail SMTP plugin
        run: |
          wp option update wp_mail_smtp --format=json  --path=wordpress \
            '{"mailer": "smtp", "smtp": {"host": "localhost", "port": "1025", "encryption": "", "auth": false}}'

      - name: Install and activate test plugin
        run: |
          cp email-test.php wordpress/wp-content/plugins/
          wp plugin activate email-test --path=wordpress

      - name: Echo received email content
        run: |
          curl -s http://localhost:8025/api/v2/messages | jq '.items[0].Content.Body' | tr -d '\"' | base64 --decode

      - name: Test email content
        run: |
          curl -s http://localhost:8025/api/v2/messages | jq '.items[0] | {subject: .Content.Headers.Subject[0], to: "\(.To[0].Mailbox)@\(.To[0].Domain)"}' > email.json

      - name: Get sent email information
        run: |
          curl -s http://localhost:8025/api/v2/messages | jq '.items[0] | {subject: .Content.Headers.Subject[0], to: "\(.To[0].Mailbox)@\(.To[0].Domain)"}' > email.json

      - name: Run pytest test script
        run: |
          pytest test_email.py
