name: Test Email

on:
  push:
    branches:
      - main

jobs:
  test_email:
    runs-on: ubuntu-latest

    services:
      mailhog:
        image: mailhog/mailhog:v1.0.1
        ports:
          - 1025:1025
          - 8025:8025

    steps:
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest test_email.py
