name: Run WordPress on GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-wordpress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start WordPress and services
        run: docker-compose up -d

      - name: Wait for WordPress to be ready
        run: sleep 20

      # - name: Install WP-CLI
      #   run: |
      #     curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
      #     chmod +x wp-cli.phar
      #     sudo mv wp-cli.phar /usr/local/bin/wp

      - name: Install WordPress and create admin user
        run: |
          wp core install --url=http://localhost:8080 --title="My WordPress Site" --admin_user=admin --admin_password=admin_password --admin_email=admin@example.com --path=/usr/src/wordpress --allow-root --skip-email
          sleep 5

      - name: Check WordPress site
        run: curl http://localhost:8080

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run E2E tests
        run: npm test

      - name: Upload screenshot as artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: registration_success.png

      - name: Cleanup
        run: docker-compose down
